dongguk_working_ant/project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('mainlistpage/', mainlistpage, name="mainlistpage"),
    path('new-post', new_post, name="new-post"),
    path('post-edit/<int:id>', post_edit, name="post-edit"),
    path('post-create/', post_create, name="post-create"),
    path('post-detail/<int:post_id>', post_detail, name="post-detail"),
    path('post-detail-review/<int:post_id>', post_detail_review, name="post-detail-review"),
    path('scrap/<int:post_id>', scraps, name="scraps"),
    path('apply/<int:post_id>', apply, name="apply"),
    path('post_edit_modal/', post_edit_modal, name="post-edit-modal"),
    path('update/<int:id>', post_update, name="post-update"),
    path('post-delete/<int:id>', post_delete, name="post-delete"),
    path('application-create/<int:post_id>', application_create, name="application-create"),
]

dongguk_working_ant/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dongguk_working_ant/project/main/models.py
from django.db import models
import json
from django.contrib.auth.models import User
# Create your models here.

class Post(models.Model):
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    organization = models.CharField(max_length=50, null=True)
    
    department = models.CharField(max_length=50, null=True)
    is_income_bracket = models.PositiveIntegerField(null=False, default=0) #boolean
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    deadline = models.DateField(null=True)
    day_left = models.IntegerField(null=True)
    place = models.CharField(max_length=50, blank=False)
    time = models.TextField(null=False)
    recruitment = models.PositiveIntegerField(default=0)
    wage = models.PositiveIntegerField(null=True, default=0)
    body = models.TextField()

    file = models.ImageField(upload_to="post/", blank=True, null=True)
    pub_date = models.DateTimeField()
    scrap = models.ManyToManyField(User, related_name='scraped', blank=True, default=None)
    scrap_count = models.PositiveIntegerField(default=0)
    applicated_count = models.PositiveIntegerField(default=0)

    #body필드에 TextField를 사용하고 JSON 문자열로 변환하여 저장 > 리스트로 만들어주기 위함
    def set_body(self, body):
        self.body = json.dumps(body)

    def get_body(self):
        return json.loads(self.body)

    def __str__(self):
        return '[' + self.organization + ']' + self.title

class Question(models.Model):
    post = models.ForeignKey(Post, null=False, blank=False, on_delete=models.CASCADE)
    content = models.TextField()
    
    def __str__(self):
        return self.content + ' from ' + str(self.post)

class Application(models.Model):
    post = models.ForeignKey(Post, null=False, related_name="applications", blank=False, on_delete=models.CASCADE)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    is_accepted = models.PositiveIntegerField(null=False, default=0) 
    file = models.FileField(upload_to="application_file/", blank=True, null=True)

class Answer(models.Model):
    application = models.ForeignKey(Application, null=False, blank=False, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, null=False, blank=False, on_delete=models.CASCADE)
    content = models.TextField()

class Review(models.Model):
    organization = models.CharField(max_length=50, null=True)
    writer = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    content = models.TextField()

dongguk_working_ant/project/main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from datetime import datetime
from django.db.models import Q, Count, F
import json
from .models import Post, Question, Application, Answer, Review
from accounts.models import Notice
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.db.models import Case, When, Value, IntegerField

# Create your views here.
def mainpage(request):
    posts = Post.objects.all()
    posts = posts.order_by('-pub_date')
    return render(request, 'main/mainpage.html', {'posts':posts})

def mainlistpage(request):
    if request.user.is_authenticated:
        
        # 입력 파라미터
        department = request.GET.get('depa','전체')
        keyword = request.GET.get('kw', '')
        sort = request.GET.get('so', '')
        end = request.GET.get('en', '')
        place = request.GET.get('pl', '')
        income = request.GET.get('inc', '')

        # 검색
        posts = Post.objects.all()

        if department == '국가':
            posts = posts.filter(department='국가')
        elif department == '교내':
            posts = posts.filter(department='교내')
        elif department == '학과':
            posts = posts.filter(~Q(department='교내'), ~Q(department='국가'), Q(department=request.user.profile.department))

        if keyword:
            posts = posts.filter(
                Q(title__icontains=keyword) |  # 제목에서 검색
                Q(organization__icontains=keyword) | #기관에서 검색
                Q(body__icontains=keyword)  # 내용에서 검색
            ).distinct()
        print(keyword)
        #마감 공고 제외 여부
        if end == 'exclude':
            posts = posts.filter(day_left__gte=0) #day_left>=0
    
        #근로 장소
        place_mapping = {
            '1': '경영/사회과학관',
            '2': '과학관',
            '3': '다향관',
            '4': '명진관',
            '5': '법학/만해관',
            '6': '본관',
            '7': '신공학관',
            '8': '남산학사',
            '9': '중앙도서관',
            '10': '원흥관',
            '11': '학림관',
            '12': '학술문화관',
            '13': '혜화관',
            '14': '기타'
        }
        if place in place_mapping:
            posts = posts.filter(place=place_mapping[place])
        
        #소득 분위 반영 여부
        if income == 'apply':
            posts = posts.filter(is_income_bracket = 1)
        elif income == 'notapply':
            posts = posts.filter(is_income_bracket = 0)

        # 정렬
        if sort == 'deadline':
            posts = posts.annotate(
                sort_deadline=Case(
                    When(day_left__lt=0, then=Value(999999)),  # 음수인 경우 큰 값 할당
                    default='day_left'  # 음수가 아닐 경우 deadline 값 사용
                )
            ).order_by('sort_deadline', '-pub_date')
        elif sort ==  'apply':
            posts = posts.order_by('-applicated_count','-pub_date')
        elif sort ==  'scrap':
            posts = posts.order_by('-scrap','-pub_date')
        else:
            posts = posts.order_by('-pub_date')
        
        context = {
            'depa': department,
            'posts': posts, 
            'kw': keyword,
            'so': sort, 
            'en': end, 
            'pl': place,
            'inc': income,
        }

        return render(request,'main/mainlistpage.html', context)
    return redirect('accounts:login')

def new_post(request):
    return render(request, 'main/new_post.html')

def post_edit(request, id):
    edit_post = get_object_or_404(Post, pk=id)

    #지원서 양식 부분
    questions = Question.objects.filter(post=id).values_list('content', flat=True)
    questions_list = list(questions)
    question_count = len(questions)

    return render(request, 'main/post_edit.html', {'post': edit_post, 'questions_list':questions_list, 'question_count':question_count})

def post_edit_modal(request):
    return render(request, 'main/post_edit_modal.html')

def post_question_create(request, num, parent_post):
    new_question = Question()
    new_question.post = parent_post
    new_question.content = request.POST['question'+str(num)]
    new_question.save()
    return new_question

def post_create(request):
    new_post = Post()

    new_post.writer = request.user
    new_post.title = request.POST['title']
    new_post.organization = request.POST['organization']
    
    new_post.department = request.POST['department']
    new_post.is_income_bracket = request.POST['is_income_bracket']
    new_post.start_date = request.POST['start_date']
    new_post.end_date = request.POST['end_date']
    new_post.deadline = request.POST['deadline']

    #남은 날짜 계산
    deadline_date = datetime.strptime(request.POST['deadline'], '%Y-%m-%d').date()
    today = timezone.now().date()
    d_day = deadline_date - today
    new_post.day_left = d_day.days

    new_post.place = request.POST['place']
    new_post.recruitment = request.POST['recruitment']
    new_post.time = request.POST['time']
    new_post.wage = request.POST['wage']

    #body부분을 리스트로 받아오기
    body_list = request.POST.getlist('body')
    new_post.set_body(body_list)  # JSON 변환 후 저장

    #new_post.file 수정 예정
    new_post.pub_date = timezone.now()
    
    new_post.save()
    
    #지원서 양식 부분
    if request.POST['question_count']:
        question_count = int(request.POST['question_count'])
        for q in range(1, question_count+1):
            post_question_create(request, q, new_post)

    return redirect('main:post-detail', new_post.id)

def post_update(request, id):
    update_post = Post.objects.get(pk=id)
    if request.user.is_authenticated and request.user == update_post.writer:
        update_post.writer = request.user
        update_post.title = request.POST['title']
        update_post.organization = request.POST['organization']
        
        update_post.department = request.POST['department']
        update_post.is_income_bracket = request.POST['is_income_bracket']
        update_post.start_date = request.POST['start_date']
        update_post.end_date = request.POST['end_date']
        update_post.deadline = request.POST['deadline']

        #남은 날짜 계산
        deadline_date = datetime.strptime(request.POST['deadline'], '%Y-%m-%d').date()
        today = timezone.now().date()
        d_day = deadline_date - today
        update_post.day_left = d_day.days

        update_post.place = request.POST['place']
        update_post.time = request.POST['time']

        recruitment_value = request.POST.get('recruitment', '')
        direct_recruitment_value = request.POST.get('direct_recruitment', '')

        if recruitment_value == 'direct' and direct_recruitment_value.isdigit():
            update_post.recruitment = int(direct_recruitment_value)
        elif recruitment_value.isdigit():
            update_post.recruitment = int(recruitment_value)
        else:
            update_post.recruitment = None

        update_post.wage = request.POST['wage']

        #body부분을 리스트로 받아오기
        body_list = request.POST.getlist('body')
        update_post.set_body(body_list)  # JSON 변환 후 저장
        
        #new_post.file 수정 예정
        update_post.pub_date = timezone.now()

        #지원서 양식 부분
        questions = Question.objects.filter(post=id)
        
        num = 1
        for q in questions: #기존에 있던 질문 수정
            q.content = request.POST['question'+str(num)]
            num += 1
            q.save()

        if int(request.POST['question_count']) > len(questions): #새로 만드는 질문 생성
            question_count = int(request.POST['question_count'])
            for q in range(num, question_count+1):
                post_question_create(request, q, update_post)

        
        update_post.save()

    return redirect('main:post-detail', update_post.id)

def post_delete(request, id):
    delete_post = Post.objects.get(pk=id)
    delete_post.delete()
    return redirect('main:mainlistpage')

def post_detail(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)
        post_body_list = post.get_body()

        applications = post.applications.all()  
        applied_users = [application.writer for application in applications]
        return render(request, 'main/post_detail.html', {'post':post, 'post_body_list':post_body_list, 'applied_users': applied_users})
    return redirect('accounts:login')

def post_detail_review(request, post_id):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=post_id)

        applications = post.applications.all()  
        applied_users = [application.writer for application in applications]  
        
        reviews = Review.objects.filter(organization=post.organization)

        return render(request, 'main/post_detail_review.html', {'post':post,'applied_users': applied_users, 'reviews':reviews})
    return redirect('accounts:login')

def scraps(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user in post.scrap.all():
        post.scrap.remove(request.user)
        post.scrap_count -= 1
        post.save()
    else:
        post.scrap.add(request.user)
        post.scrap_count += 1
        post.save()

    previous_url = request.META.get('HTTP_REFERER', 'main:mainlistpage')
    return HttpResponseRedirect(previous_url)
    
def apply(request, post_id):
    questions = Question.objects.filter(post=post_id)
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'main/apply.html', {'questions':questions, 'post':post})

def application_create(request, post_id):
    new_application = Application()

    post = get_object_or_404(Post, pk=post_id)
    new_application.post = post
    new_application.writer = request.user

    #지원자수 추가
    post.applicated_count += 1

    new_application.save()
    post.save()

    #지원서 내용 부분
    questions = Question.objects.filter(post=new_application.post)
    num=1
    for question in questions:
            new_answer = Answer()
            new_answer.application = new_application

dongguk_working_ant/project/main/templates/main/post_detail.html
<!--교직원,학생 알아보기 상세공고 페이지 담당:이동건-->
<!--ldg_workdetailpage-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/main/post_detail.css'%}"
/>
<div class="detailpageScreen">
    <!--뒤로가기 버튼-->
    <div class="backBtn">
        <a href="javascript:history.back()" class="backBtnAtag">
            <img src="{% static 'images/icons/back.svg' %}" />
        </a>
    </div>
    <!--화면 내용 전체 프레임 박스사이gap72-->
    <div class="detailpageFrame">
        <!--상세공고 내용들어가는 박스1 -->
        <div class="detailBox1">
            <div class="box1Frame">
                <!--박스1 상단 인덱스 + 교직원기준 수정,삭제 버튼 프레임 -->
                <div class="box1TopFrame">
                    <!--박스1 상단 인덱스 프레임 -->
                    <div class="box1IndexFrame">
                        <div class="box1Index"><span class="box1IndexText">{{post.department}}</span></div>
                        <!-- 소득분위 반영 미반영 체크 -->
                        <div class="box1Index">
                            {% if post.is_income_bracket == 0 %}
                                <span class="box1IndexText">소득분위 미반영</span>
                            {% elif post.is_income_bracket == 1 %}
                                <span class="box1IndexText">소득분위 반영</span>
                            {% endif %}
                        
                        </div>
                        <div class="box1Index"><span class="box1IndexText">{{ post.recruitment }}명</span></div>
                    </div>
                    <!--박스1 상단 우측 수정,삭제버튼  로그인에 따라 구현 -->
                    {% if post.writer == user %} <!--게시글 작성자일 때-->
                        <div class="box1EditFrame">
                            <a href="{% url 'main:post-edit' id=post.id %}" class="box1Btn" id="EditBtn">수정</a>
                            <a href="{% url 'main:post-delete' id=post.id %}" class="box1Btn" id="DeleteBtn">삭제</a>
                        </div>
                    {% endif %}
                </div>
                <div class="box1Content1Frame">
                    <div class="box1TitleFrame">
                        <div class="box1Title">[{{post.organization}}] {{ post.title }}</div>
                        <div class="box1organization">{{post.place}}</div>
                    </div>
                    <div class="deadlineFrame">
                        {% if post.day_left >= 0 %}
                            <div class="deadline">~{{post.deadline}} 마감 {{post.day_left}}일 전</div>
                        {% else %}
                            <div class="deadline">모집마감</div>
                        {% endif %}
                        <div class="box1line"></div>
                    </div>
                    <div class="box1etcFrame">
                        <div class="etcWage">
                            <img src="{% static 'images/icons/money.svg' %}" />
                            <div class="etcText">시급<br>{{ post.wage }}원</div>
                        </div>
                        <div class="etcDate">
                            <img src="{% static 'images/icons/period.svg' %}" />
                            <div class="etcText">활동 기간<br>{{post.start_date}}~{{post.end_date}}</div>
                        </div>
                        <div class="etcTime">
                            <img src="{% static 'images/icons/date.svg' %}" />
                            <div class="etcText">요일 및 시간
                                <br>
                                {{post.time}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--세부사항 목차+박스프레임 -->
        <div class="detailBox2Frame">
            <!--세부사항 목차 아이콘?-->
            <div class="index">
                <a href="{% url 'main:post-detail' post.id %}">
                    <button class="indexB" id="detail" style="background-color: #FE902F; color: #FFFDFB;">세부사항</button>
                </a>
                <a href="{% url 'main:post-detail-review' post.id %}">
                    <button class="indexB" id="review">근로후기</button>
                </a>
            </div>
            <!--세부사항 내용 들어가는 박스2-->
            <div class="detailBox2">
                <div class="box2Frame">
                    {% for body in post_body_list %}
                        {% if body %}
                            <div class="check">
                                <img class="profileImage"src="{% static 'images/icons/check.svg' %}" />
                                <span class="box2Text">
                                    {{body}}<br>
                                </span>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                
            </div>
        </div>
        <!--지원하기 버튼-->
        {% if user.profile.student_or_staff == 'student' %}
            {% if post.day_left >= 0 %}
                {% if user not in applied_users %}
                    <div class="applyBtn">
                        <a href="{% url 'main:apply' post.id %}" class="applyBtnAtag">
                            <span class="applyBtnContent">
                                지원하기
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25" viewBox="0 0 24 25" fill="none">
                                    <path d="M6.5 17.9897L18.3647 6.125M18.3647 6.125H7.50011M18.3647 6.125V15.9888" stroke="#FFFDFB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </span>
                        </a>
                    </div>
                {% else %}
                    <div class="applyBtn">
                        <span class="applyBtnContent">
                            지원 완료
                        </span>
                    </div>
                {% endif %}
            {% else %}
                <div class="applyBtn">
                    <span class="applyBtnContent">
                        모집 마감
                    </span>
                </div>
            {% endif %}
        {% endif %}
    </div>

</div>

<!-- <script src="{% static 'js/main/workDetailPage.js' %}"></script> -->
{% endblock %} 
{% block footer %}
    <!--footer필요없는페이지라 비우기 -->
{% endblock %}

dongguk_working_ant/project/main/templates/main/post_detail_review.html
<!--교직원,학생 알아보기 상세공고 페이지 담당:이동건-->
<!--ldg_workdetailpage-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/main/post_detail.css'%}"
/>
<div class="detailpageScreen">
    <!--뒤로가기 버튼-->
    <div class="backBtn">
        <a href="javascript:history.back()" class="backBtnAtag">
            <img src="{% static 'images/icons/back.svg' %}" />
        </a>
    </div>
    <!--화면 내용 전체 프레임 박스사이gap72-->
    <div class="detailpageFrame">
        <!--상세공고 내용들어가는 박스1 -->
        <div class="detailBox1">
            <div class="box1Frame">
                <!--박스1 상단 인덱스 + 교직원기준 수정,삭제 버튼 프레임 -->
                <div class="box1TopFrame">
                    <!--박스1 상단 인덱스 프레임 -->
                    <div class="box1IndexFrame">
                        <div class="box1Index"><span class="box1IndexText">{{post.department}}</span></div>
                        <!-- 소득분위 반영 미반영 체크 -->
                        <div class="box1Index">
                            {% if post.is_income_bracket == 0 %}
                                <span class="box1IndexText">소득분위 미반영</span>
                            {% elif post.is_income_bracket == 1 %}
                                <span class="box1IndexText">소득분위 반영</span>
                            {% endif %}
                        
                        </div>
                        <div class="box1Index"><span class="box1IndexText">{{ post.recruitment }}명</span></div>
                    </div>
                    <!--박스1 상단 우측 수정,삭제버튼  로그인에 따라 구현 -->
                    {% if post.writer == user %} <!--게시글 작성자일 때-->
                        <div class="box1EditFrame">
                            <a href="{% url 'main:post-edit' id=post.id %}" class="box1Btn" id="EditBtn">수정</a>
                            <a href="{% url 'main:post-delete' id=post.id %}" class="box1Btn" id="DeleteBtn">삭제</a>
                        </div>
                    {% endif %}
                </div>
                <div class="box1Content1Frame">
                    <div class="box1TitleFrame">
                        <div class="box1Title">[{{post.organization}}] {{ post.title }}</div>
                        <div class="box1organization">{{post.place}}</div>
                    </div>
                    <div class="deadlineFrame">
                        {% if post.day_left >= 0 %}
                            <div class="deadline">~{{post.deadline}} 마감 {{post.day_left}}일 전</div>
                        {% else %}
                            <div class="deadline">모집마감</div>
                        {% endif %}
                        <div class="box1line"></div>
                    </div>
                    <div class="box1etcFrame">
                        <div class="etcWage">
                            <img src="{% static 'images/icons/money.svg' %}" />
                            <div class="etcText">시급<br>{{ post.wage }}원</div>
                        </div>
                        <div class="etcDate">
                            <img src="{% static 'images/icons/period.svg' %}" />
                            <div class="etcText">활동 기간<br>{{post.start_date}}~{{post.end_date}}</div>
                        </div>
                        <div class="etcTime">
                            <img src="{% static 'images/icons/date.svg' %}" />
                            <div class="etcText">요일 및 시간
                                <br>
                                {{post.time}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--세부사항 목차+박스프레임 -->
        <div class="detailBox2Frame">
            <!--세부사항 목차 아이콘?-->
            <div class="index">
                <a href="{% url 'main:post-detail' post.id %}">
                    <button class="indexB" id="detail" >세부사항</button>
                </a>
                <a href="{% url 'main:post-detail-review' post.id %}">
                    <button class="indexB" id="review" style="background-color: #FE902F; color: #FFFDFB;">근로후기</button>
                </a>
            </div>
            <!--세부사항 내용 들어가는 박스2-->
            {% for review in reviews %}
                <div class="detailBox2" style="height: 156px; display: flex; justify-content: center; align-items: center;">
                    <div class="box2Frame" style=" display: flex; flex-direction: row; gap:34px; "  >
                        <div class="reImg" style>
                            <img src="{% static 'images/icons/Component4.svg' %}" />
                        </div>
                        <div  class="reviewtext" style="height:100%; display: flex; flex-direction: column; justify-content: center; align-items: flex-start;">
                            <div id="nAme" style="display: flex;">{{review.writer.profile.name.0 }}**</div>
                            <div id="reView"style="display: flex;">{{review.content}}</div>
                        </div>
                        
                    </div>
                </div>
            {% endfor %}
        </div>
        <!--지원하기 버튼-->
        {% if user.profile.student_or_staff == 'student' %}
            {% if post.day_left >= 0 %}
                {% if user not in applied_users %}
                    <div class="applyBtn">
                        <a href="{% url 'main:apply' post.id %}" class="applyBtnAtag">
                            <span class="applyBtnContent">
                                지원하기
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25" viewBox="0 0 24 25" fill="none">
                                    <path d="M6.5 17.9897L18.3647 6.125M18.3647 6.125H7.50011M18.3647 6.125V15.9888" stroke="#FFFDFB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                                </svg>
                            </span>
                        </a>
                    </div>
                {% else %}
                    <div class="applyBtn">
                        <span class="applyBtnContent">
                            지원 완료
                        </span>
                    </div>
                {% endif %}
            {% else %}
                <div class="applyBtn">
                    <span class="applyBtnContent">
                        모집 마감
                    </span>
                </div>
            {% endif %}
        {% endif %}
    </div>

</div>

<!-- <script src="{% static 'js/main/workDetailPage.js' %}"></script> -->
{% endblock %} 
{% block footer %}
    <!--footer필요없는페이지라 비우기 -->
{% endblock %}

dongguk_working_ant/project/main/templates/main/workDetailPage.html
<!--교직원,학생 알아보기 상세공고 페이지 담당:이동건-->
<!--ldg_workdetailpage-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/main/workDetailPage.css'%}"
/>

<div class="detailpageScreen">
    <!--뒤로가기 버튼-->
    <div class="backBtn">
        <a href="{% url 'main:mainlistpage' %}" class="backBtnAtag">
            <svg xmlns="http://www.w3.org/2000/svg" width="52" height="52" viewBox="0 0 52 52" fill="none">
                <g clip-path="url(#clip0_1089_3134)">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M17.9664 27.5327C17.5602 27.1264 17.332 26.5754 17.332 26.0009C17.332 25.4264 17.5602 24.8754 17.9664 24.4691L30.2232 12.2122C30.4231 12.0053 30.6622 11.8402 30.9265 11.7267C31.1909 11.6131 31.4752 11.5534 31.7629 11.5509C32.0506 11.5484 32.3359 11.6032 32.6021 11.7121C32.8684 11.8211 33.1103 11.9819 33.3138 12.1854C33.5172 12.3888 33.6781 12.6307 33.787 12.897C33.896 13.1633 33.9508 13.4486 33.9483 13.7363C33.9458 14.024 33.886 14.3083 33.7725 14.5726C33.6589 14.837 33.4938 15.076 33.2869 15.2759L22.5619 26.0009L33.2869 36.7259C33.6816 37.1345 33.9 37.6818 33.895 38.2499C33.8901 38.818 33.6622 39.3615 33.2605 39.7632C32.8588 40.1649 32.3154 40.3928 31.7473 40.3977C31.1792 40.4026 30.6319 40.1843 30.2232 39.7896L17.9664 27.5327Z" fill="black"/>
                </g>
                <defs>
                <clipPath id="clip0_1089_3134">
                <rect width="52" height="52" fill="white"/>
                </clipPath>
                </defs>
            </svg>
        </a>
    </div>
    <!--화면 내용 전체 프레임 박스사이gap72-->
    <div class="detailpageFrame">
        <!--상세공고 내용들어가는 박스1 -->
        <div class="detailBox1">
            <div class="box1ContentFrame">
                너무 크다...
                <div class="">
                    <p>[{{post.organization}}] {{ post.title }}</p>
                    <p>장소: {{ post.place }}</p>
                    <p>부서: {{ post.department }}</p>
                    <p>시간: {{ post.time }}</p>
                    <p>기타 세부사항: {{ post.details }}</p>
                </div>
            </div>
        </div>
        <!--세부사항 목차+박스프레임 -->
        <div class="detailBox2Frame">
            <!--세부사항 목차 아이콘?-->
            <div class="index">
                <span class="indexText">세부사항</span>
            </div>
            <!--세부사항 내용 들어가는 박스2-->
            <div class="detailBox2">

            </div>
        </div>
        <!--지원하기 버튼-->
        <div class="applyBtn">
            <a href="{% url 'main:mainpage' %}" class="applyBtnAtag"><!--url수정하기-->
                <span class="applyBtnContent">
                    지원하기
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25" viewBox="0 0 24 25" fill="none">
                        <path d="M6.5 17.9897L18.3647 6.125M18.3647 6.125H7.50011M18.3647 6.125V15.9888" stroke="#FFFDFB" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </span>
            </a>
        </div>
    </div>

</div>

<script src="{% static 'js/main/workDetailPage.js' %}"></script>
{% endblock %} 
{% block footer %}
    <!--footer필요없는페이지라 비우기 -->
{% endblock %}