dongguk_working_ant/project/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup-choose/', signup_choose, name="signup-choose"),
    path('signup-student/', signup_student, name="signup-student"),
    path('signup-staff/', signup_staff, name="signup-staff"),
    path('delete-account/', delete_account, name="delete-account"),
]

dongguk_working_ant/project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('mainlistpage/', mainlistpage, name="mainlistpage"),
    path('new-post', new_post, name="new-post"),
    path('post-edit/<int:id>', post_edit, name="post-edit"),
    path('post-create/', post_create, name="post-create"),
    path('post-detail/<int:post_id>', post_detail, name="post-detail"),
    path('post-detail-review/<int:post_id>', post_detail_review, name="post-detail-review"),
    path('scrap/<int:post_id>', scraps, name="scraps"),
    path('apply/<int:post_id>', apply, name="apply"),
    path('post_edit_modal/', post_edit_modal, name="post-edit-modal"),
    path('update/<int:id>', post_update, name="post-update"),
    path('post-delete/<int:id>', post_delete, name="post-delete"),
    path('application-create/<int:post_id>', application_create, name="application-create"),
]

dongguk_working_ant/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dongguk_working_ant/project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here

class Profile(models.Model):
    student_or_staff = models.CharField(max_length=20, blank=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=5, blank=False)

    #gender    
    GENDER_M = "male"
    GENDER_F = "female"
    GENDER_CHOICES = (
    	(GENDER_M, "Male"),
        (GENDER_F, "Female"),
    )
    gender = models.CharField(choices=GENDER_CHOICES, max_length=10, blank=True)

    birth = models.DateField(blank=False, null=True)
    
    photo = models.ImageField(upload_to="user_photo/", blank=True)
    department = models.CharField(max_length=20, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    email = models.CharField(max_length=50, blank=False)
    student_number = models.CharField(max_length=10, blank=False)
    income = models.PositiveIntegerField(null=True, default=0)
    certification_student = models.FileField(upload_to="student_certification/", blank=True)
    certification_staff = models.FileField(upload_to="staff_certification/",blank=True)
    #scraped = models.ManyToManyField()

class Notice(models.Model):
    user = models.ForeignKey(User, null=False, blank=False, on_delete=models.CASCADE)
    content = models.CharField(max_length=20, blank=True)
    link = models.CharField(max_length=20, blank=True)
    pub_date = models.DateTimeField()

    def summary(self):
        return self.content[:22]

dongguk_working_ant/project/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from .models import Profile
from django.contrib.auth.models import User

# Create your views here.

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request,user)
            return redirect('main:mainpage')
        else:
            return render(request,'accounts/login.html')

    elif request.method == 'GET':
        return render(request, 'accounts/login.html')
    
def logout(request):
    auth.logout(request)
    return redirect('main:mainpage')

def signup_choose(request):
    return render(request, 'accounts/signup_choose.html')

def signup_student(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                username = request.POST['username'],
                password = request.POST['password'],
            )

            student_or_staff = 'student'
            name = request.POST['name']
            gender = request.POST['gender']
            birth = request.POST['birth']
            department = request.POST['department']
            phone = request.POST['phone']
            email = request.POST['email']
            student_number = request.POST['student_number']
            income = request.POST['income']

            certification_student = request.FILES.get('certification_student')
            photo = request.FILES.get('photo')

            profile = Profile(student_or_staff=student_or_staff, user=user, name=name, gender=gender, birth=birth, department=department, phone=phone, email=email)

            if certification_student:
                profile.certification_student = certification_student
            if photo:
                profile.photo = photo

            profile.save()

            auth.login(request, user)
            return redirect('/')

    return render(request, 'accounts/signup_student.html')

def signup_staff(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['confirm']:
            user = User.objects.create_user(
                username = request.POST['username'],
                password = request.POST['password'],
            )

            student_or_staff = 'staff'
            name = request.POST['name']
            email = request.POST['email']
            if request.FILES.get('certification_staff'):
                certification = request.FILES['certification_staff']

            profile = Profile(student_or_staff=student_or_staff, user=user, name=name, email=email)
            if request.FILES.get('certification_staff'):
                profile = Profile(certification=certification)

            profile.save()

            auth.login(request, user)
            return redirect('/')

    return render(request, 'accounts/signup_staff.html')

def delete_account(request):
    request.user.delete()
    return redirect('main:mainlistpage')

dongguk_working_ant/project/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="loginFrame">
    <form action="{% url 'accounts:login' %}" method="POST">
        {% csrf_token %}
        
        <div class="logo">
            <img src="{% static 'images/icons/login.svg' %}" />
        </div>
        <div id="line">
            <a href="{% url 'accounts:signup-choose' %}">
                <img src="{% static 'images/icons/loginline.svg' %}" />
            </a>
        </div>
        <div class="login">

                <input id="ID"type="text" name="username" placeholder="아이디를 입력해 주세요." >

                <input id="PW" type="password" name="password" placeholder="비밀번호를 입력해 주세요." >

        </div>
        <div class="btn">
            <input type="submit" value="로그인">
        </div>
            
    </form>
</div>
<style>
    .loginFrame{
        display: flex;
        width: 100%;
        /* height: 100%; */
        flex-direction: column;
        justify-content: center;
        /* margin-bottom: 100px; */
        align-items: center;
        /* border: solid 1px blue; */
    }
    .logo{
        display: flex;
        justify-content: center;
    }
    .login{
        margin-top: 60px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        gap:20px;
    }
    .line{
        margin-top:40px;
    }
    #ID, #PW{
        width: 336px;
        height: 48px;
        flex-shrink: 0;
        border-radius: 10px;
        border: 1px solid #E4E4E4;
        background: rgba(255, 255, 255, 0.40);
        padding-left: 20px;
        outline: none;
        color: rgba(85, 84, 80, 0.60);

        font-family: "SUITE Variable";
        font-size: 16px;
        font-style: normal;
        font-weight: 400;
        line-height: normal;
    }
    input:focus {
            border: 1px solid #ccc; /* 포커스 시에도 동일한 테두리 색 */
    }
    .btn{
        margin-top: 50px;
        display: flex;
        justify-content: center;

    }
    .btn input{
        display: flex;
        justify-content: center;
        width: 110px;
        height: 44px;
        gap: 8px;
        border-radius: 50px;
        border: 1px solid #FE902F;
        background: #FE902F;
        color: #FFF;

        text-align: center;
        font-family: "SUITE Variable";
        font-size: 18px;
        font-style: normal;
        font-weight: 500;
        line-height: normal;
    }

</style>
{% endblock %}

dongguk_working_ant/project/accounts/templates/accounts/signup_choose.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<a href="{% url 'accounts:signup-student' %}">
    학생 회원가입
</a>
<br>
<a href="{% url 'accounts:signup-staff' %}">
    교직원 회원가입
</a>
{% endblock %}

dongguk_working_ant/project/accounts/templates/accounts/signup_staff.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'accounts:signup-staff' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>아이디</p>
    <input type="text" name="username">
    <br>

    <p>비밀번호</p>
    <input type="password" name="password">
    <br>

    <p>비밀번호 확인</p>
    <input type="password" name="confirm">
    <br>

    <p>이름</p>
    <input type="text" name="name">
    <br>

    <p>이메일</p>
    <input type="email" name="email" maxlength="64" pattern="[a-zA-Z0-9]+[@][a-zA-Z0-9]+[.]+[a-zA-Z]+[.]*[a-zA-Z]*" required>
    <br>

    <p>교직원증명서</p>
    <input type="file" name="certification_staff">
    <br>
    
    <input type="submit" value="회원가입">
</form>

{% endblock %}

dongguk_working_ant/project/accounts/templates/accounts/signup_student.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form action="{% url 'accounts:signup-student' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>아이디</p>
    <input type="text" name="username">
    <br>

    <p>비밀번호</p>
    <input type="password" name="password">
    <br>

    <p>비밀번호 확인</p>
    <input type="password" name="confirm">
    <br>

    <p>이름</p>
    <input type="text" name="name">
    <br>

    <p>성별: </p>
    <input type="radio" name="gender" value="GENDER_M" checked="checked">남성
    <input type="radio" name="gender" value="GENDER_F">여성
    <br>

    <p>생년월일: </p>
    <input type="date" name="birth" min="1900-01-01" max="2024-01-01" required>
    <br>

    <p>전화번호</p>
    <input type="text" name="phone">
    <br>

    <p>이메일</p>
    <input type="email" name="email" maxlength="64" pattern="[a-zA-Z0-9]+[@][a-zA-Z0-9]+[.]+[a-zA-Z]+[.]*[a-zA-Z]*" required>
    <br>

    <p>학과</p>
    <input type="text" name="department">
    <br>

    <p>학번</p>
    <input type="text" name="student_number">
    <br>

    <p>소득분위</p>
    <input type="number" name="income">
    <br>

    <p>사진</p>
    <input type="file" name="photo">
    <br>

    <p>학생증명서</p>
    <input type="file" name="certification_student">
    <br>
    
    <input type="submit" value="회원가입">
</form>

{% endblock %}