dongguk_working_ant/project/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup-choose/', signup_choose, name="signup-choose"),
    path('signup-student/', signup_student, name="signup-student"),
    path('signup-staff/', signup_staff, name="signup-staff"),
    path('delete-account/', delete_account, name="delete-account"),
]

dongguk_working_ant/project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('mainlistpage/', mainlistpage, name="mainlistpage"),
    path('new-post', new_post, name="new-post"),
    path('post-edit/<int:id>', post_edit, name="post-edit"),
    path('post-create/', post_create, name="post-create"),
    path('post-detail/<int:post_id>', post_detail, name="post-detail"),
    path('post-detail-review/<int:post_id>', post_detail_review, name="post-detail-review"),
    path('scrap/<int:post_id>', scraps, name="scraps"),
    path('apply/<int:post_id>', apply, name="apply"),
    path('post_edit_modal/', post_edit_modal, name="post-edit-modal"),
    path('update/<int:id>', post_update, name="post-update"),
    path('post-delete/<int:id>', post_delete, name="post-delete"),
    path('application-create/<int:post_id>', application_create, name="application-create"),
]

dongguk_working_ant/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dongguk_working_ant/project/users/urls.py
from django.urls import path
from .views import *
# from users import views #추가한코드

app_name = "users"
urlpatterns = [
    path('staff-mypage/', staff_mypage, name="staff-mypage"),
    path('staff-appslist/<int:post_id>', staff_appslist, name="staff-appslist"),
    path('staff-mypost/', staff_mypost, name="staff-mypost"),
    path('staff-studentappfile/<int:post_id>/<int:student_id>', staff_studentappfile, name="staff-studentappfile"),
    path('student-myapplication/', student_myapplication, name="student-myapplication"),
    path('student-mypage/', student_mypage, name="student-mypage"),
    path('student-myscrap/', student_myscrap, name="student-myscrap"),
    path('student-mywork/', student_mywork, name="student-mywork"),
    path('check-result/<int:post_id>', check_result, name="check-result"),
    path('notice/', notice, name="notice"),
    path('review-content/', review_content, name="review-content"),
    path('student-myappfile/<int:post_id>', student_myappfile, name="student-myappfile"),
]

dongguk_working_ant/project/project/templates/shared/_topnav.html
<!--
최상단 네비게이션을 구현한 topnav 입니다.
3개의 section으로 구분되어있습니다.
-->

<!-- 스타일 css import -->
{% load static %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/shared/topnav.css'%}"
/>

<div class="screen">
  <div class="topnav">
    <!-- 로그인 회원가입-->
    <div class="nav-1 header-font">
      <div class="div">
        <!-- 로그인을 한 경우 -->
        <div class="nav-2">
          <a class="Caption" href="{% url 'main:mainlistpage' %}" id="arabogy"
            >알아보기</a
          >
          {% if user.profile.student_or_staff == 'student' %}
          <!--학생일 때-->
          <a class="Caption" href="{% url 'users:student-myapplication' %}"
            >지원현황</a
          >
          {% elif user.profile.student_or_staff == 'staff' %}<!--교직원일 때-->
          <a class="Caption" href="{% url 'main:new-post' %}">게시하기</a>
          {% else %}
          <!--로그인하지 않았거나 어드민일 때-->
          <a class="Caption" href="{% url 'users:student-myapplication' %}"
            >지원현황</a
          >
          {% endif %}
        </div>
        <a class="logo logo-font" href="{% url 'main:mainpage' %}">
          <img src="{% static 'images/logo.svg' %}" />
        </a>
        <div class="nav-3">
          {% if user.is_authenticated %}
          <a class="Caption" href="/accounts/logout/">로그아웃</a>
          {% if user.profile.student_or_staff == 'student' %}
          <!--학생일 때-->
          <a class="Caption" href="{% url 'users:student-mypage' %}">MY</a>
          {% elif user.profile.student_or_staff == 'staff' %}<!--교직원일 때-->
          <a class="Caption" href="{% url 'users:staff-mypage' %}">MY</a>
          {% else %}
          <!--어드민일 때-->
          <a class="Caption" href="{% url 'users:staff-mypage' %}">MY</a>
          {% endif %}

          <!-- 로그인을 하지 않은 경우 -->
          {% else %}
          <ul class="nav-link-account">
            <a class="Caption gray" href="{% url 'accounts:signup-choose' %}"
              >회원가입</a
            >
            <!--회원가입 페이지-->
            <a class="Caption gray" href="{% url 'accounts:login' %}">로그인</a>
            <!--로그인 페이지-->
          </ul>
          {% endif %}
          <div>
            <button id="bell">
              <img src="{% static 'images/icons/bell.svg' %}" class="bell" />
            </button>
            <!--모달-->
            <div id="topnav_modal" style="display: none; z-index: 99;">
              <div style="font-size: 16px; font-weight: 700px; color: #FE902F; margin-bottom: 7px;">알림</div>
              <!--내용 추가..-->
              <div id="notice-container" style="display: block">
                <!--<div class="Caption gray"></div>-->
                <!--<div class="Caption gray"><img src="{% static 'images/icons/x.svg' %}" style="margin-right: 3px;" onclick="delete_alarm(this)"/>{{notice.content}}</div>-->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  // 알람
  const bell = document.getElementById("bell");
  const topnav_modal = document.getElementById("topnav_modal");
  bell.addEventListener("click", function () {
      if (topnav_modal.style.display == "none") {
          topnav_modal.style.display = "flex";

          // AJAX 요청 보내기
          fetch('{% url "users:notice" %}', {
              method: "GET",
              headers: {
                  "X-Requested-With": "XMLHttpRequest",
                  "Content-Type": "application/json",
              },
          })
          .then((response) => response.json())
          .then((data) => {
              // 데이터 받아서 모달에 표시
              const notices = data.notices;
              let noticeContent = "";
              notices.forEach((notice) => {
                  const detailUrl = `{% url 'main:post-detail' 0 %}`.replace(
                      "0",
                      notice.link
                  );
                  const noticeId = `notice-${notice.id}`;
                  const noticeClass = localStorage.getItem(noticeId) === "seen" ? "seen" : "new";

                  noticeContent += `
                      <div id="${noticeId}" class="Caption gray modal_con ${noticeClass}" style="margin-bottom: 13px;" onclick="show(this);">
                          <img src="{% static 'images/icons/background_blank.svg' %}" id='blank-img' onclick="delete_alarm(this)"/>
                          <a href="${detailUrl}">
                              <span>${notice.summary}...</span>
                          </a>
                      </div>
                  `;
              });
              document.getElementById("notice-container").innerHTML = noticeContent;

              // 새로 생성된 .Caption 요소들에 이벤트 리스너 추가
              const newCaptions = document.getElementsByClassName("Caption");
              for (let caption of newCaptions) {
                  caption.addEventListener(
                      "mouseover",
                      function (event) {
                          event.target.style.color = "#FF8A00";
                      },
                      false
                  );
                  caption.addEventListener(
                      "mouseout",
                      function (event) {
                          event.target.style.color = "";
                      },
                      false
                  );
              }

              topnav_modal.style.display = "flex";
          })
          .catch((error) => console.error("Error:", error));
      } else if (topnav_modal.style.display == "flex") {
          topnav_modal.style.display = "none";
      }
  });

  // 알람 보면 배경색 변경
  function show(modal_con) {
      modal_con.classList.remove("new");
      modal_con.classList.add("seen");
      localStorage.setItem(modal_con.id, "seen");
  }

  document.addEventListener("DOMContentLoaded", function () {
      const captions = document.getElementsByClassName("modal_con");
      console.log(captions);

      for (let caption of captions) {
          const bgState = localStorage.getItem(caption.id);
          if (bgState === "seen") {
              caption.classList.remove("new");
              caption.classList.add("seen");
          }
      }
  });
</script>