dongguk_working_ant/project/accounts/urls.py
from django.urls import path
from .views import *

app_name = "accounts"
urlpatterns = [
    path('login/', login, name="login"),
    path('logout/', logout, name="logout"),
    path('signup-choose/', signup_choose, name="signup-choose"),
    path('signup-student/', signup_student, name="signup-student"),
    path('signup-staff/', signup_staff, name="signup-staff"),
    path('delete-account/', delete_account, name="delete-account"),
]

dongguk_working_ant/project/main/urls.py
from django.urls import path
from .views import *

app_name = "main"
urlpatterns = [
    path('', mainpage, name="mainpage"),
    path('mainlistpage/', mainlistpage, name="mainlistpage"),
    path('new-post', new_post, name="new-post"),
    path('post-edit/<int:id>', post_edit, name="post-edit"),
    path('post-create/', post_create, name="post-create"),
    path('post-detail/<int:post_id>', post_detail, name="post-detail"),
    path('post-detail-review/<int:post_id>', post_detail_review, name="post-detail-review"),
    path('scrap/<int:post_id>', scraps, name="scraps"),
    path('apply/<int:post_id>', apply, name="apply"),
    path('post_edit_modal/', post_edit_modal, name="post-edit-modal"),
    path('update/<int:id>', post_update, name="post-update"),
    path('post-delete/<int:id>', post_delete, name="post-delete"),
    path('application-create/<int:post_id>', application_create, name="application-create"),
]

dongguk_working_ant/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [ 
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('users/', include('users.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dongguk_working_ant/project/users/urls.py
from django.urls import path
from .views import *
# from users import views #추가한코드

app_name = "users"
urlpatterns = [
    path('staff-mypage/', staff_mypage, name="staff-mypage"),
    path('staff-appslist/<int:post_id>', staff_appslist, name="staff-appslist"),
    path('staff-mypost/', staff_mypost, name="staff-mypost"),
    path('staff-studentappfile/<int:post_id>/<int:student_id>', staff_studentappfile, name="staff-studentappfile"),
    path('student-myapplication/', student_myapplication, name="student-myapplication"),
    path('student-mypage/', student_mypage, name="student-mypage"),
    path('student-myscrap/', student_myscrap, name="student-myscrap"),
    path('student-mywork/', student_mywork, name="student-mywork"),
    path('check-result/<int:post_id>', check_result, name="check-result"),
    path('notice/', notice, name="notice"),
    path('review-content/', review_content, name="review-content"),
    path('student-myappfile/<int:post_id>', student_myappfile, name="student-myappfile"),
]

dongguk_working_ant/project/users/models.py
from django.db import models

# Create your models here.

dongguk_working_ant/project/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from main.models import Post, Application, Answer, Review
from accounts.models import Notice
from django.contrib.auth.models import User
from django.utils import timezone
from django.http import JsonResponse

# Create your views here.
def staff_mypage(request):
    return render(request, 'users/staff_mypage.html')

#지원한 학생 리스트 페이지
def staff_appslist(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    applications = Application.objects.filter(post_id=post_id)
    
    return render(request, 'users/staff_appslist.html', {'applications': applications, 'post': post})

def staff_mypost(request):
    posts = Post.objects.filter(writer=request.user.id)
    return render(request, 'users/staff_mypost.html', {'posts':posts})

#학생 지원서 내용 페이지
def staff_studentappfile(request, post_id, student_id):
    post = get_object_or_404(Post, pk=post_id)
    application = get_object_or_404(Application, writer_id=student_id, post_id=post_id)
    student = get_object_or_404(User, id=student_id)
    answers = Answer.objects.filter(application=application)
    return render(request, 'users/staff_studentappfile.html',{'application':application, 'answers':answers, 'student':student, 'post':post})

def student_myapplication(request):
    #post = get_object_or_404(Post)
    if request.user.is_authenticated:

        applications = Application.objects.filter(writer=request.user)
        applications = applications.order_by('-is_accepted')
        return render(request, 'users/student_myapplication.html', {'applications':applications})
    return redirect('accounts:login')

def student_mypage(request):
    return render(request, 'users/student_mypage.html')

def student_myscrap(request):
    scraped_posts = request.user.scraped.all()
    post_data = []

    for post in scraped_posts:
        has_application = Application.objects.filter(post=post, writer=request.user).exists()
        post_data.append({'post': post, 'has_application': has_application})

    return render(request, 'users/student_myscrap.html', {'post_data': post_data})

def student_mywork(request):
    mywork = Application.objects.filter(writer=request.user, is_accepted=2).select_related('post')
    mywork_posts = [application.post for application in mywork]
    return render(request, 'users/student_mywork.html', {'mywork_posts': mywork_posts})

def check_result(request, post_id):
    if request.method == "POST":
        checked_applications = request.POST.getlist('check')
        
        for app in checked_applications:
            application = get_object_or_404(Application, pk=app)

            #학생에게 알림전송
            new_notice = Notice()
            new_notice.user = application.writer
            
            if request.POST.get('result')== '합격':
                application.is_accepted = 2
                new_notice.content = '합격 | [' + application.post.organization + ']' + application.post.title
            elif request.POST.get('result') == '불합격':
                application.is_accepted = 1
                new_notice.content = '불합격 | [' + application.post.organization + ']' + application.post.title
            application.save()

            new_notice.link = str(application.post.id)
            new_notice.pub_date = timezone.now()
            new_notice.save()

    return redirect('users:staff-appslist', post_id)

def notice(request):
    notices = Notice.objects.filter(user=request.user)
    notice_list = [{'summary': notice.summary(), 'link': int(notice.link)} for notice in notices]
    return JsonResponse({'notices': notice_list})

def review_content(request):
    if request.user.is_authenticated:
        new_review = Review()
        post_num = int(request.POST['post_id'])

        post = get_object_or_404(Post, pk=post_num)

        new_review.organization = post.organization

        new_review.writer = request.user

        new_review.content = request.POST.get('review')

        new_review.save()

        return redirect('users:student-mywork')
    return redirect('accounts:login')


def student_myappfile(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    application = get_object_or_404(Application, writer=request.user, post_id=post_id)
    student = get_object_or_404(User, id=request.user.id)
    answers = Answer.objects.filter(application=application)
    return render(request, 'users/staff_studentappfile.html',{'application':application, 'answers':answers, 'student':student, 'post':post})

dongguk_working_ant/project/users/templates/users/staff_appslist.html
<!--교직원 지원자 리스트 담당자: 이동건!-->


{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/users/staff_appslist.css'%}"
/>
<!-- {% for student in students %}
    {{ student.profile.name }}
{% endfor %} -->
<form action="{% url 'users:check-result' post.id %}" method="POST" enctype="multipart/form-data">
{% csrf_token %}
<div class="appslist">
    <!--뒤로가기 +제목 -->
    <div class="title">
        <div class="backBtn">
            <a href="javascript:history.back()" class="backBtnAtag">
                <img src="{% static 'images/icons/back.svg' %}" />
            </a>
            <span id="word">{{post.organization}} {{post.title}} 지원현황</span>
        </div>
    </div>
    <!--지원자리스트 목록 라디오태그 -->
    <div class="cardFrame">
        {% for app in applications %}
            <div class="card">
                <div class="cardPadding">
                    <div class="cardContent">
                        <!--라디오버튼인척하는 체크박스 
                        라디오버튼은 하나만 클릭돼서 이렇게함 -->
                            {% if app.is_accepted == 0 %} <!--결과 없음-->
                            <div class="fake">
                                <!--{{ forloop.counter }}이거는 for문개수를 숫자로 표현해주는거임 맨처음 카드가1그다음이 2 이런식-->
                                <input type="checkbox" id="checkbox{{ forloop.counter }}" class="custom-checkbox" name="check" value="{{app.id}}">
                                <label for="checkbox{{ forloop.counter }}" class="custom-label"></label>
                            </div>
                        {% elif app.is_accepted == 1 %} <!--불합격-->
                            <div class="fake">
                                <img class="passFail" src="{% static 'images/icons/faillee.svg' %}" />
                            </div>
                            
                        {% elif app.is_accepted == 2 %} <!--합격-->
                            <div class="fake">
                                <img class="passFail" src="{% static 'images/icons/passlee.svg' %}" />    
                            </div>
                            
                        {% endif %}
                        <div class="img">
                            <div class="profileImage">
                                <img src="{{ app.writer.profile.photo.url }}" />
                            </div>
                        </div>
                        <div class="cardText">
                            <span class="ct"><span class="ct" id="bold">{{ app.writer.profile.name }}</span>{{app.writer.profile.birth}}</span>
                            <span class="ct">{{app.writer.profile.department}} | {{app.writer.profile.student_number}}</span>
                        </div>
                    </div>
                    <div class="cardBtnFrame">
                        <a href="{% url 'users:staff-studentappfile' post.id app.writer.id %}">
                            <div class="cardBtn">지원서 확인</div>
                        </a>
                    </div>
                </div>
                
            </div>
        {% endfor %}
        <div class="passfail">
            <button type="button" class="appBtn" id="pass">합격</button>
            <button type="button" class="appBtn" id="fail">불합격</button>
        </div>
    </div>
</div>


    <!-- 합격 모달 -->
    <div class="modal" id="passModal">
        <div class="modal-content">
            <div class="comment">합격 처리하시겠습니까?</div>
            <div class="bt">
                <button type="button" class="modalBtn" id="passConfirm">확인</button>
                <button type="button" class="modalBtn" id="cancel">취소</button>
            </div>
            
        </div>
    </div>

    <!-- 불합격 모달 -->
    <div class="modal" id="failModal">
        <div class="modal-content">
            <div class="comment">불합격 처리하시겠습니까?</div>
            <div class="bt">
                <button type="button"class="modalBtn" id="failConfirm">확인</button>
                <button type="button" class="modalBtn" id="cancel">취소</button>
            </div>
            
        </div>
    </div>

    <!-- 결과 모달 -->
    <div class="modal" id="resultModal">
        <div class="modal-content">
            <div id="resultMessage"></div>
            <input type="hidden" name="result" id="result" value="{{ result }}">
            <button type="submit" class="modalBtn" id="resultClose">확인</button>
        </div>
    </div>
</form>
<script src="{% static 'js/users/staff_appslist.js' %}"></script>
{% endblock %} 
{% block footer %}
    <!--footer필요없는페이지라 비우기 -->
{% endblock %}

dongguk_working_ant/project/users/templates/users/staff_mypage.html
<!--교직원 마이페이지 담당자:이동건-->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/users/staff_mypage.css'%}"
/>
<style>
    #arabogy {
    color: black;
    }
    .nav-3 :nth-child(2){
        color: #FF8A00
    }
</style>
<div class="staffScreen">
    <div class="staffBody">
        <div class="staffProfile">
            <div class="profileImage">
                <img class="profileImage"src="{% static 'images/icons/imgprofile.svg' %}" />
            </div>
            <div class="profileText">
                <span ><span id="mpTc">{{ user.profile.name }}</span>님,</span><span>안녕하세요!</span>
            </div>
        </div>
        <div class="staffNavBox">
            <div class="staffNav">
                <a class="nav" href="{% url 'main:new-post' %}">
                    <img src="{% static 'images/icons/staffmypagenav2.svg' %}" />
                </a>
                <a class="nav" href="{% url 'users:staff-mypost' %}">
                    <img src="{% static 'images/icons/staffmypagenav3.svg' %}" />
                </a>
                <!-- 스크랩 -->
                <a class="nav" href="{% url 'users:student-myscrap' %}">
                    <img src="{% static 'images/icons/studentnav4.svg' %}" />
                </a>
            </div>
            <div class="staffLogoutNav">
                <a href="{% url 'accounts:logout' %}">
                    <button class="logoutNav"><span class="logoutNavText">로그아웃</span></button>
                </a>
                <a href="{% url 'accounts:delete-account' %}">
                    <button class="logoutNav"><span class="logoutNavText">회원탈퇴</span></button>
                </a>
            </div>
        </div>
    </div>
</div>


<!-- <script src="{% static 'js/main/mainpage.js' %}"></script>  js쓸거면 링크수정-->
{% endblock %} 
{% block footer %}
    {% include 'shared/_footer.html' %}
{% endblock %}

dongguk_working_ant/project/users/templates/users/staff_mypost.html
<!--교직원마이페이지 공고관리 (지원자확인) 담당자: 이정진-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/users/staff_mypost.css'%}"
/>
<style>
    #arabogy {
    color: black;
    }
    .nav-3 :nth-child(2){
        color: #FF8A00
    }
</style>
<div class="test">
<div class="content" id="header">
    <a href="javascript:history.back()">
        <img src="{% static 'images/icons/vector.svg' %}" id="vector">
    </a>
    <span class="Capital Caption" style="margin-left:-0.5em; margin-bottom:0.5em;">공고관리</span>
</div>

<div class="content" id="main2">
    {% if posts %}
        {% for post in posts %}
        <div class="card">
            <div class="more_function">
                <a href="{% url 'main:post-edit' id=post.id %}">
                    <img src="{% static 'images/icons/fix.svg' %}">
                </a>
                <a href="{% url 'main:post-delete' id=post.id %}">
                    <button type="button" name="trash" onclick="delete_Card(this)"> <!--화면에서는 사라지는데 DB에서도 제거되어야 함-->
                        <img src="{% static 'images/icons/trash.svg' %}">
                    </button>
                </a>
            </div>
            <span class="photo">
                <span class="architecture">
                    <!--건물 사진 적용-->
                    {% if post.place == '경영/사회과학관' %}
                        <img src="{% static 'images/buildings/경영사회과학관.png' %}" alt="cardImage">
                    {% elif post.place == '과학관' %}
                        <img src="{% static 'images/buildings/과학관.png' %}" alt="cardImage" >
                    {% elif post.place == '남산학사' %}
                        <img src="{% static 'images/buildings/남산학사.png' %}" alt="cardImage" >
                    {% elif post.place == '다향관' %}
                        <img src="{% static 'images/buildings/다향관.png' %}" alt="cardImage" >
                    {% elif post.place == '명진관' %}
                        <img src="{% static 'images/buildings/명진관.png' %}" alt="cardImage" >
                    {% elif post.place == '법학/만해관' %}
                        <img src="{% static 'images/buildings/법학만해관.png' %}" alt="cardImage" >
                    {% elif post.place == '본관' %}
                        <img src="{% static 'images/buildings/본관.png' %}" alt="cardImage" >
                    {% elif post.place == '신공학관' %}
                        <img src="{% static 'images/buildings/신공학관.png' %}" alt="cardImage" >
                    {% elif post.place == '원흥관' %}
                        <img src="{% static 'images/buildings/원흥관.png' %}" alt="cardImage" >
                    {% elif post.place == '정보문화관' %}
                        <img src="{% static 'images/buildings/정보문화관.png' %}" alt="cardImage" >
                    {% elif post.place == '중앙도서관' %}
                        <img src="{% static 'images/buildings/중앙도서관.png' %}" alt="cardImage" >
                    {% elif post.place == '학림관' %}
                        <img src="{% static 'images/buildings/학림관.png' %}" alt="cardImage" >
                    {% elif post.place == '학술문화관' %}
                        <img src="{% static 'images/buildings/학술문화관.png' %}" alt="cardImage" >
                    {% elif post.place == '혜화관' %}
                        <img src="{% static 'images/buildings/혜화관.png' %}" alt="cardImage" >
                    {% elif post.place == '기타' %}
                        <img src="{% static 'images/buildings/기타.png' %}" alt="cardImage" >    
                    {% endif %}
                </span>
            </span>
            <span class="detail">
                <div class="information">
                    <span class="info classification small orange">
                        #{{post.department}}
                    </span>
                    <span class="info date small white">
                        {% if post.day_left >= 0 %}
                            {{ post.day_left }}일 남음
                        {% else %}
                            모집마감
                        {% endif %}
                    </span>
                    <span class="info classification small orange"> <!--인원 수 넣어주세요-->
                        #{{post.department}}
                    </span>
                </div>
                <a class="title Caption big" href="{% url 'main:post-detail' post.id %}"> <!--url 수정 부탁드립니다-->
                    [{{post.organization}}] {{post.title}}
                </a>
                <div class="Caption light up">
                    <div>{{post.place}}</div>
                    <div>{{post.time}}</div>
                </div>
            </span>
            <a href="{% url 'users:staff-appslist' post.id %}" class="more_info"> <!--url 수정 부탁드립니다-->
                <img src="{% static 'images/icons/check_applicator.svg' %}"/>
            </a>
        </div>
        {% endfor %}
    {% endif %}
</div>
</div>

<script src="{% static 'js/users/staff_mypost.js' %}"></script>

{% endblock %}

dongguk_working_ant/project/users/templates/users/student_myapplication.html
<!-- 학생 마이페이지 지원현황페이지 이정진-->
{% extends 'base.html' %} {% load static %} {% block content %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/users/student_myapplication.css'%}"
/>
<style>
  #arabogy {
    color: black;
    }
    .nav-3 :nth-child(2){
        color: #FF8A00
    }
</style>
<div class="test">
<div class="content" id="header">
  <a href="javascript:history.back()">
    <img src="{% static 'images/icons/vector.svg' %}" id="vector" />
  </a>
  <span class="Capital Caption" style="margin-bottom: 0.5em">지원 현황</span>
</div>

<div class="content" id="main2">
  {% if applications %} {% for app in applications %}
  <div class="card">
    <span class="photo">
      <span class="architecture">
        {% if app.post.place == '경영/사회과학관' %}
            <img src="{% static 'images/buildings/경영사회과학관.png' %}" alt="cardImage">
        {% elif app.post.place == '과학관' %}
            <img src="{% static 'images/buildings/과학관.png' %}" alt="cardImage" >
        {% elif app.post.place == '남산학사' %}
            <img src="{% static 'images/buildings/남산학사.png' %}" alt="cardImage" >
        {% elif app.post.place == '다향관' %}
            <img src="{% static 'images/buildings/다향관.png' %}" alt="cardImage" >
        {% elif app.post.place == '명진관' %}
            <img src="{% static 'images/buildings/명진관.png' %}" alt="cardImage" >
        {% elif app.post.place == '법학/만해관' %}
            <img src="{% static 'images/buildings/법학만해관.png' %}" alt="cardImage" >
        {% elif app.post.place == '본관' %}
            <img src="{% static 'images/buildings/본관.png' %}" alt="cardImage" >
        {% elif app.post.place == '신공학관' %}
            <img src="{% static 'images/buildings/신공학관.png' %}" alt="cardImage" >
        {% elif app.post.place == '원흥관' %}
            <img src="{% static 'images/buildings/원흥관.png' %}" alt="cardImage" >
        {% elif app.post.place == '정보문화관' %}
            <img src="{% static 'images/buildings/정보문화관.png' %}" alt="cardImage" >
        {% elif app.post.place == '중앙도서관' %}
            <img src="{% static 'images/buildings/중앙도서관.png' %}" alt="cardImage" >
        {% elif app.post.place == '학림관' %}
            <img src="{% static 'images/buildings/학림관.png' %}" alt="cardImage" >
        {% elif app.post.place == '학술문화관' %}
            <img src="{% static 'images/buildings/학술문화관.png' %}" alt="cardImage" >
        {% elif app.post.place == '혜화관' %}
            <img src="{% static 'images/buildings/혜화관.png' %}" alt="cardImage" >
        {% elif app.post.place == '기타' %}
            <img src="{% static 'images/buildings/기타.png' %}" alt="cardImage" >    
        {% endif %}
      </span>
      <!--DB에 사진이 추가되면 삭제될 거임-->
    </span>
    <span class="detail">
      <div class="information">
        <span class="info classification small orange">
          #{{app.post.department}}
        </span>
        <span class="info date small white">
          {% if app.post.day_left >= 0 %} {{ app.post.day_left }}일 남음 {% else %} 지원
          마감 {% endif %}
        </span>
        <span class="info classification small orange">
          {{app.post.applicated_count}}/{{app.post.recruitment}}명
        </span>
      </div>
      <a class="title Caption big" href="{% url 'main:post-detail' app.post.id %}">
        <!--url 수정 부탁드립니다-->
        [{{app.post.organization}}] {{app.post.title}}
      </a>
      <div class="Caption light up">
        <div>{{app.post.place}}</div>
        <div>{{app.post.time}}</div>
      </div>
    </span>
    <div class="more_info">
      {% if app.is_accepted == 1 %} <!--불합격-->
        <img src="{% static 'images/icons/fail.svg' %}" />
      {% elif app.is_accepted == 2 %} <!--합격-->
        <img src="{% static 'images/icons/pass.svg' %}" />
      {% else %} <!--미정-->
      {% endif %}
      <a href="{% url 'users:student-myappfile' app.post.id %}">
        <img id="plz" src="{% static 'images/icons/plz.svg' %}" />
      </a>
    </div>
  </div>
  {% endfor %} {% endif %}
</div>
</div>

<script src="{% static 'js/users/staff_mypost.js' %}"></script>

{% endblock %}

dongguk_working_ant/project/users/templates/users/student_mypage.html
<!-- 학생마이페이지 이동건 -->

{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/users/student_mypage.css'%}"
/>
<style>
    #arabogy {
    color: black;
    }
    .nav-3 :nth-child(2){
        color: #FF8A00
    }
</style>
<div class="staffScreen">
    <div class="staffBody">
        <div class="staffProfile">
            <div class="profileImage">
                <img src="{{ user.profile.photo.url }}" />
            </div>
            <div class="profileText">
                <span ><span id="mpTc">{{ user.profile.name }}</span>님,</span><span>안녕하세요!</span>
            </div>
        </div>
        <div class="staffNavBox">
            <div class="staffNav">
                </a>
                <!-- 나의근로 -->
                <a class="nav" href="{% url 'users:student-mywork' %}"> 
                    <img src="{% static 'images/icons/studentnav2.svg' %}" />
                </a>
                <!-- 지원현황 -->
                <a class="nav" href="{% url 'users:student-myapplication' %}"> 
                    <img src="{% static 'images/icons/studentnav3.svg' %}" />
                </a>
                <!-- 스크랩 -->
                <a class="nav" href="{% url 'users:student-myscrap' %}">
                    <img src="{% static 'images/icons/studentnav4.svg' %}" />
                </a>
            </div>
            <div class="staffLogoutNav">
                <a href="{% url 'accounts:logout' %}">
                    <button class="logoutNav"><span class="logoutNavText">로그아웃</span></button>
                </a>
                <a href="{% url 'accounts:delete-account' %}">
                    <button class="logoutNav"><span class="logoutNavText">회원탈퇴</span></button>
                </a>
            </div>
        </div>
    </div>
</div>


<!-- <script src="{% static 'js/main/mainpage.js' %}"></script>  js쓸거면 링크수정-->
{% endblock %} 
{% block footer %}
    {% include 'shared/_footer.html' %}
{% endblock %}

dongguk_working_ant/project/users/templates/users/student_myscrap.html
<!-- 학생-마이페이지-스크랩 이정진 -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link
    rel="stylesheet"
    type="text/css"
    href="{% static 'css/users/staff_mypost.css'%}"
/>
<style>
    #arabogy {
    color: black;
    }
    .nav-3 :nth-child(2){
        color: #FF8A00
    }
</style>
<div class="test">
<div class="content" id="header">
    <a href="javascript:history.back()">
        <img src="{% static 'images/icons/vector.svg' %}" id="vector">
    </a>
    <span class="Capital Caption" style="margin-bottom:0.5em;">스크랩</span>
</div>

<div class="content" id="main2">
    {% if post_data %}
        {% for data in post_data %}
        <div class="card">
            <form action="{% url 'main:scraps' data.post.id %}" method='POST'> <!--스크랩-->
                {% csrf_token %}
                <button name="star" class="star" value="none">
                    {% if request.user in data.post.scrap.all %}
                        <img src="{% static 'images/icons/blink_star.svg' %}"/>
                    {% else %}
                        <img src="{% static 'images/icons/star.svg' %}"/>
                    {% endif %}
                </button>
            </form>
            <span class="photo">
                <span class="architecture">
                    <!--건물 사진 적용-->
                    {% if data.post.place == '경영/사회과학관' %}
                        <img src="{% static 'images/buildings/경영사회과학관.png' %}" alt="cardImage">
                    {% elif data.post.place == '과학관' %}
                        <img src="{% static 'images/buildings/과학관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '남산학사' %}
                        <img src="{% static 'images/buildings/남산학사.png' %}" alt="cardImage" >
                    {% elif data.post.place == '다향관' %}
                        <img src="{% static 'images/buildings/다향관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '명진관' %}
                        <img src="{% static 'images/buildings/명진관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '법학/만해관' %}
                        <img src="{% static 'images/buildings/법학만해관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '본관' %}
                        <img src="{% static 'images/buildings/본관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '신공학관' %}
                        <img src="{% static 'images/buildings/신공학관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '원흥관' %}
                        <img src="{% static 'images/buildings/원흥관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '정보문화관' %}
                        <img src="{% static 'images/buildings/정보문화관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '중앙도서관' %}
                        <img src="{% static 'images/buildings/중앙도서관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '학림관' %}
                        <img src="{% static 'images/buildings/학림관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '학술문화관' %}
                        <img src="{% static 'images/buildings/학술문화관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '혜화관' %}
                        <img src="{% static 'images/buildings/혜화관.png' %}" alt="cardImage" >
                    {% elif data.post.place == '기타' %}
                        <img src="{% static 'images/buildings/기타.png' %}" alt="cardImage" >    
                    {% endif %}
                </span>
            </span>
            <span class="detail">
                <div class="information">
                    <span class="info classification small orange">
                        #{{data.post.department}}
                    </span>
                    <span class="info date small white">
                        {% if data.post.day_left >= 0 %}
                            {{ data.post.day_left }}일 남음
                        {% else %}
                            모집마감
                        {% endif %}
                    </span>
                </div>
                <a class="title Caption big" href="{% url 'main:post-detail' data.post.id %}">
                    [{{data.post.organization}}] {{data.post.title}}
                </a>
                <div class="Caption light up">
                    <div>{{data.post.place}}</div>
                    <div>{{data.post.time}}</div>
                </div>
            </span>

            {% if data.has_application %}
            <div class="more_info">
                <img src="{% static 'images/icons/complete_applicate.svg' %}"/>
            </div>
            {% endif %}
        </div>
        {% endfor %}
    {% endif %}
</div>
</div>

<script src="{% static 'js/users/staff_mypost.js' %}"></script>

{% endblock %}